### ISSUE TITLE
No tags can't be found

### ISSUE THREAD

**Issue by baptistedonaux** [n0madic/gitlab-registry-images-cleaner#5]
Hi ! and thanks for your job.

I'm really interesting to test your project. When I runs your project, I can see this error. Any idea ?

```bash
$ ./gricleaner.py --ini=gricleaner.ini --dry-run --debug -r foo/bar
[2018-04-10 11:51:51,197] INFO     Found 1 repositories
[2018-04-10 11:51:51,197] INFO     SCAN repository: foo/bar
[2018-04-10 11:51:51,199] DEBUG    Starting new HTTPS connection (1): git.foo.bar
[2018-04-10 11:51:51,308] DEBUG    https://git.foo.bar:443 "GET /jwt/auth/?service=container_registry&scope=repository:foo/bar:* HTTP/1.1" 200 None
[2018-04-10 11:51:51,312] DEBUG    Starting new HTTPS connection (1): registry.foo.bar
[2018-04-10 11:51:51,376] DEBUG    https://registry.foo.bar:443 "GET /v2/foo/bar/tags/list HTTP/1.1" 404 None
Traceback (most recent call last):
  File "./gricleaner.py", line 192, in <module>
    tags = GRICleaner.get_tags(repository)
  File "./gricleaner.py", line 50, in get_tags
    "repository:" + repo)
  File "./gricleaner.py", line 35, in get_json
    json_r = response.json()
  File "/root/gitlab-registry-images-cleaner-master/__env__/local/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by n0madic** [comment]
Judging by
> DEBUG    https://registry.foo.bar:443 "GET /v2/foo/bar/tags/list HTTP/1.1" 404 None   

the docker registry returned 404 because it did not find the specified repository or tags for it.

In GitLab, there is a situation where there is an empty registry in the repository, it is displayed in the directory, but there are no tags in it.

**Comment by baptistedonaux** [comment]
I have checked. In my case, I have images but no one with `latest` tag. I have a specific tag defined.

**Comment by n0madic** [comment]
Unfortunately I do not know why the docker registry does not find tags for this repository ... And without this list, the utility can not be further worked ...

If you scan the entire image catalog without specifying the repository, then the same error?

**Comment by baptistedonaux** [comment]
Yes, I have the same error in two cases.

**Comment by n0madic** [comment]
The utility makes a standard [API request](https://docs.docker.com/registry/spec/api/#listing-image-tags).
Unfortunately, there is nothing more to be done from this side ...
